// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbbztujsobvftdijfocq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYnp0dWpzb2J2ZnRkaWpmb2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjc5NzAsImV4cCI6MjA3MDY0Mzk3MH0.o0nN5Mj_tWD8YJhEzxLdYYWdPmltPmSR4JszxRdI7xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});